config/routes.rb
ThemePark::Application.routes.draw do |map|
  resources :fastpasses

  resources :customers

  resources :attractions

  resources :amber_alerts

  get "main/index"
  
  get "event/index"
  
  get 'view_attractions' => 'view_attractions#index'
  
  get 'view_events' => 'view_events#index'

  get 'view_amber_alerts' => 'view_amber_alerts#index'

  get 'view_park_info' => 'view_park_info#index'
  
  get 'view_fastpasses' => 'view_fastpasses#index'
  
  get 'submit_fast_pass' => 'submit_fast_pass#index'
  
  get 'cust_fastpass' => 'cust_fastpass#index'
  
  get 'att_fastpass' => 'att_fastpass#index'
  
  controller :sessions do
    get 'login_admin' => :new
    post 'login_admin' => :create
    delete 'logout_admin' => :destroy
  end
  
  controller :sessions_cust do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :events
  
  map.connect 'submit_fast_pass/avail_times', :controller => 'submit_fast_pass', :action => 'avail_times'
  
  map.connect 'submit_fast_pass/add_pass', :controller => 'submit_fast_pass', :action => 'add_pass'
  
  map.connect 'fastpasses/use', :controller => 'fastpasses', :action => 'use'
  

  root :to => 'main#index', :as => 'main'

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  skip_before_filter :customerauthorize
  
  # GET /attractions
  # GET /attractions.xml
  def index
    @attractions = Attraction.all
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @attractions }
    end
  end

  # GET /attractions/1
  # GET /attractions/1.xml
  def show
    @attraction = Attraction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attraction }
    end
  end

  # GET /attractions/new
  # GET /attractions/new.xml
  def new
    @attraction = Attraction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @attraction }
    end
  end

  # GET /attractions/1/edit
  def edit
    @attraction = Attraction.find(params[:id])
  end

  # POST /attractions
  # POST /attractions.xml
  def create
    @attraction = Attraction.new(params[:attraction])

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to(@attraction, :notice => 'Attraction was successfully created.') }
        format.xml  { render :xml => @attraction, :status => :created, :location => @attraction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @attraction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /attractions/1
  # PUT /attractions/1.xml
  def update
    @attraction = Attraction.find(params[:id])

    respond_to do |format|
      if @attraction.update_attributes(params[:attraction])
        format.html { redirect_to(@attraction, :notice => 'Attraction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attraction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.xml
  def destroy
    @attraction = Attraction.find(params[:id])
    @attraction.destroy

    respond_to do |format|
      format.html { redirect_to(attractions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_for(@attraction) do |f| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :attraction_type %><br />
    <%= f.text_field :attraction_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :min_height %><br />
    <%= f.text_field :min_height %>
  </div>
  <div class="field">
    <%= f.label :is_fastpass %><br />
    <%= f.text_field :is_fastpass %>
  </div>
  <div class="field">
    <%= f.label :fee %><br />
    <%= f.text_field :fee %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing attraction</h1>

<%= render 'form' %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<h1>Attractions</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Minimum Height</th>
    <th>FastPass?</th>
    <th>Fee</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attractions.each do |attraction| %>
  <tr>
    <td><%= attraction.name %></td>
    <td><%= attraction.attraction_type %></td>
    <td>
      <% if attraction.min_height.nil? || attraction.min_height==0 %>
        NONE
      <% else %>
        <%= attraction.min_height %> inches
      <% end %></td>
    <% if attraction.is_fastpass == 1 %>
      <td>Yes</td>
    <% else %>
      <td>No</td>
    <% end %>
    <td>
      <% if attraction.fee.nil? || attraction.fee==0 %>
        $0.00
      <% else %>
        <%= number_to_currency(attraction.fee) %>
      <% end %></td>
    <td><%= link_to 'View', attraction %></td>
    <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
    <td><%= link_to 'Delete', attraction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to '>> New Attraction', new_attraction_path %>

app/views/attractions/new.html.erb
<h1>New attraction</h1>

<%= render 'form' %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>


<p class="image">
  <%= image_tag(@attraction.photo) %>
</p>

<p>
  <b>Name:</b>
  <%= @attraction.name %>
</p>

<p>
  <b>Type:</b>
  <%= @attraction.attraction_type %>
</p>

<p>
  <b>Description:</b>
  <%= @attraction.description %>
</p>

<p>
  <b>Minimum Height:</b>
  <%= @attraction.min_height %> inches
</p>

<p>
  <b>FastPass Available?:</b>
  <% if @attraction.is_fastpass == 1 %>
    <td>Yes</td>
  <% else %>
    <td>No</td>
  <% end %>
</p>

<p>
  <b>Fee:</b>
  <% if @attraction.fee.nil? || @attraction.fee==0 %>
    $0.00
  <% else %>
    <%= number_to_currency(@attraction.fee) %>
  <% end %>
</p>

<p>
  <% if @attraction.is_fastpass==1 %>
    <% session[:att_id] = @attraction.id %>
    <%= link_to 'FastPasses for this Attraction', att_fastpass_path %>
  <% end %>
</p>


<%= link_to 'Edit', edit_attraction_path(@attraction) %> |
<%= link_to 'Back', attractions_path %>